CREATE TABLE IF NOT EXISTS `cityrentals_rentals` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `citizenid` VARCHAR(50) NOT NULL,
    `vehicle_key` VARCHAR(64) NOT NULL,
    `vehicle_model` VARCHAR(64) NOT NULL,
    `vehicle_label` VARCHAR(128) NOT NULL,
    `category` VARCHAR(32) NOT NULL,
    `plate` VARCHAR(12) NOT NULL,
    `duration_type` VARCHAR(16) NOT NULL,
    `duration_value` INT NOT NULL,
    `price_paid` INT NOT NULL DEFAULT 0,
    `damage_fee` INT NOT NULL DEFAULT 0,
    `late_fee` INT NOT NULL DEFAULT 0,
    `payment_method` VARCHAR(16) NOT NULL DEFAULT 'bank',
    `status` VARCHAR(24) NOT NULL DEFAULT 'pending_delivery',
    `delivery_x` FLOAT DEFAULT 0,
    `delivery_y` FLOAT DEFAULT 0,
    `delivery_z` FLOAT DEFAULT 0,
    `starts_at` DATETIME DEFAULT NULL,
    `expires_at` DATETIME DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX `idx_citizenid` (`citizenid`),
    INDEX `idx_status` (`status`),
    INDEX `idx_plate` (`plate`)
);
